export const IS_OPEN_SIDEBAR = "IS_OPEN_SIDEBAR";
export const GET_PRODUCT_BEGIN = "GET_PRODUCT_BEGIN";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";
export const GET_SINGLE_PRODUCT_BEGIN = "GET_SINGLE_PRODUCT_BEGIN";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";

export const LOAD_PRODUCT = "LOAD_PRODUCT";
export const SET_LIST_VIEW_PRODUCT = "SET_LIST_VIEW_PRODUCT";
export const SET_GRID_VIEW_PRODUCT = "SET_GRID_VIEW_PRODUCT";

export const UPDATE_SORT = "UPDATE_SORT";
export const SORT_PRODUCT = "SORT_PRODUCT";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const FILTER_PRODUCT = "FILTER_PRODUCT";
export const CLEAR_FILTER = "CLEAR_FILTER";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const CLEAR_SHOPPING_CART = "CLEAR_SHOPPING_CART";
export const INCREASE_AMOUNT = "INCREASE_AMOUNT";
export const DESCREASE_AMOUNT = "DESCREASE_AMOUNT";
export const COUNT_TOTAL_PRICE = "COUNT_TOTAL_PRICE";
export const COUNT_TOTAL_AMOUNT = "COUNT_TOTAL_AMOUNT";

